# Generated by Django 4.2.3 on 2023-07-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
