# Generated by Django 4.2.3 on 2023-07-09 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0002_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentemail',
            options={'verbose_name': 'письмо для рассылки', 'verbose_name_plural': 'письма для рассылки'},
        ),
        migrations.AlterModelOptions(
            name='sendsettings',
            options={'verbose_name': 'настройка рассылки', 'verbose_name_plural': 'настройки рассылок'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_content',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_send_settings',
        ),
        migrations.AddField(
            model_name='emaillogs',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail_sender.sendsettings'),
        ),
        migrations.AddField(
            model_name='sendsettings',
            name='customer',
            field=models.ManyToManyField(blank=True, null=True, to='mail_sender.customer', verbose_name='Клиенты'),
        ),
        migrations.AddField(
            model_name='sendsettings',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail_sender.contentemail', verbose_name='Текст рассылки'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='sendsettings',
            name='period',
            field=models.CharField(choices=[('OD', 'Once a day'), ('OW', 'Once a week'), ('OM', 'Once a month')], default='OM', max_length=2, verbose_name='Частота рассылки'),
        ),
        migrations.AlterField(
            model_name='sendsettings',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('IP', 'In Progress'), ('CL', 'Closed')], default='CA', max_length=2, verbose_name='Статус'),
        ),
    ]
