# Generated by Django 4.2.3 on 2023-07-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0003_alter_contentemail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsettings',
            name='name',
            field=models.CharField(default='test', max_length=150, verbose_name='название рассылки'),
            preserve_default=False,
        ),
    ]
