# Generated by Django 4.2.3 on 2023-07-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0004_sendsettings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsettings',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('IP', 'In Progress'), ('CL', 'Closed')], default='CR', max_length=2, verbose_name='Статус'),
        ),
    ]
